Repository Harsh2255/Basic-Data-Structure, pull requests merged in 2020-10, with the labels that each got.

#2 Complexity reduced
  d-heapSrt.java
Labels: good first issue

#4 v1 for the interpolation search normal approach
  InterpolationSrc.java
Labels: good first issue

#3 jump search
  jumpSRC.java
Labels: good first issue, help wanted

#5 Create Fractional_KnapSack_Problem.java
  Fractional_KnapSack_Problem.java
Labels: hacktoberfest-accepted

#6 Create TreeSet.java
  TreeSet.java
Labels: hacktoberfest-accepted

#7 Create KnapsackProblem.java
  KnapsackProblem.java
Labels: hacktoberfest-accepted

#9 Create OuickSrt.java
  OuickSrt.java
Labels: good first issue, hacktoberfest-accepted

#8 BubbleSrt.java
  BubbleSrt.java
Labels: good first issue, hacktoberfest-accepted

#14 Update jumpSRC.java
  jumpSRC.java
Labels: good first issue, hacktoberfest-accepted

#13 Create Prefix_to_inflix.java
  Prefix_to_inflix.java
Labels: good first issue, hacktoberfest-accepted

#30 Update KnapsackProblem.java
  KnapsackProblem.java
Labels: good first issue, hacktoberfest-accepted

#31 Update KnapsackProblem.java
  KnapsackProblem.java
Labels: good first issue, hacktoberfest-accepted

#32 Update MergeSrt.java
  MergeSrt.java
Labels: good first issue, hacktoberfest-accepted

#33 Update MergeSrt.java
  MergeSrt.java
Labels: hacktoberfest-accepted

#34 Update MergeSrt.java
  MergeSrt.java
Labels: hacktoberfest-accepted, help wanted

#35 Update MergeSrt.java
  MergeSrt.java
Labels: good first issue, hacktoberfest-accepted

#36 Update InterpolationSrc.java
  InterpolationSrc.java
Labels: good first issue, hacktoberfest-accepted
